#!/usr/bin/env python3
"""
Parse iPhone backup message format from OCR'd text
"""

import re
import json
import sys
from datetime import datetime
from typing import List, Dict, Optional
from dateutil import parser as date_parser


def parse_iphone_backup_messages(text: str) -> Dict:
    """
    Parse iPhone backup message format.
    Format:
        YYYY-MM-DD HH:MM:SS (UTC -8)
        Message text
        
        OR
        
        YYYY-MM-DD HH:MM:SS (UTC -8)
        From +XXXXXXXXXXX (Name):
        Message text
    """
    
    # Identify participants
    # Phone owner is not prefixed with "From"
    # Other person is "From +14088391455 (Jan Valderrama)" or similar
    
    participant_patterns = re.findall(r'From \+\d+ \(([^)]+)\):', text)
    if participant_patterns:
        other_person = max(set(participant_patterns), key=participant_patterns.count)
    else:
        other_person = "Jan Marie Hales"  # From filename
    
    # Phone owner - try to extract from the context
    phone_owner = "Michael"  # Could extract from filename/path
    
    participants = {
        "Person_A": phone_owner,
        "Person_B": other_person
    }
    
    print(f"Identified participants: {phone_owner} and {other_person}")
    
    # Parse messages
    messages = []
    lines = text.split('\n')
    
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        
        # Look for timestamp pattern
        timestamp_match = re.match(r'(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \(UTC [+-]\d+\)', line)
        
        if timestamp_match:
            timestamp_str = timestamp_match.group(1)
            try:
                msg_date = datetime.strptime(timestamp_str, '%Y-%m-%d %H:%M:%S')
            except:
                msg_date = None
            
            # Check next lines for message
            i += 1
            
            # Check if next line is "From ..." pattern
            sender = "Person_A"  # Default to phone owner
            if i < len(lines):
                from_match = re.match(r'From \+\d+ \(([^)]+)\):', lines[i].strip())
                if from_match:
                    sender = "Person_B"
                    i += 1  # Skip the "From" line
            
            # Collect message text until next timestamp or empty line
            message_lines = []
            while i < len(lines):
                next_line = lines[i].strip()
                
                # Stop if we hit another timestamp
                if re.match(r'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} \(UTC [+-]\d+\)', next_line):
                    break
                
                # Stop at page markers
                if 'Page ' in next_line and 'Generated by' in next_line:
                    break
                
                # Stop at header lines
                if next_line.startswith('Messages with') or next_line.endswith('Messages /'):
                    break
                
                # Skip certain patterns
                if next_line in ['MISSING', 'ATTACHMENT', '©', '®', '0']:
                    i += 1
                    continue
                
                # Add non-empty lines
                if next_line:
                    message_lines.append(next_line)
                
                i += 1
            
            # Create message if we have text
            message_text = ' '.join(message_lines).strip()
            if message_text and len(message_text) > 3:
                # Filter out likely noise
                if not message_text.startswith('http') or len(message_text) > 50:
                    messages.append({
                        'sender': sender,
                        'participant_id': sender,
                        'participant_name': participants[sender],
                        'text': message_text,
                        'date': msg_date,
                        'raw_date': timestamp_str
                    })
            
            continue
        
        i += 1
    
    # Sort by date
    messages.sort(key=lambda x: x['date'] if x['date'] else datetime.min)
    
    # Get date range
    dates = [m['date'] for m in messages if m['date']]
    date_range = {
        'start': min(dates).isoformat() if dates else None,
        'end': max(dates).isoformat() if dates else None
    }
    
    return {
        'participants': participants,
        'messages': messages,
        'total_messages': len(messages),
        'date_range': date_range
    }


def main():
    if len(sys.argv) < 2:
        print("Usage: python parse_iphone_backup.py <ocr_text_file> [output_json]")
        print("\nExample:")
        print("  python parse_iphone_backup.py ocr_raw_text.txt conversation_data.json")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "conversation_data.json"
    
    print(f"Loading OCR text from: {input_file}")
    with open(input_file, 'r', encoding='utf-8') as f:
        text = f.read()
    
    print(f"Text length: {len(text)} characters")
    
    print("\nParsing messages...")
    result = parse_iphone_backup_messages(text)
    
    print(f"\nParsing complete!")
    print(f"Participants: {list(result['participants'].values())}")
    print(f"Total messages: {result['total_messages']}")
    print(f"Date range: {result['date_range']['start']} to {result['date_range']['end']}")
    
    # Save to JSON
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(result, f, indent=2, default=str)
    
    print(f"Data saved to: {output_file}")
    
    # Show sample messages
    if result['messages']:
        print("\n=== Sample Messages ===")
        for i, msg in enumerate(result['messages'][:5]):
            print(f"\n{msg['participant_name']} ({msg['raw_date']}):")
            print(f"  {msg['text'][:100]}...")
        
        if len(result['messages']) > 5:
            print(f"\n... and {len(result['messages']) - 5} more messages")


if __name__ == "__main__":
    main()
